[[pages]]
path = "streamlit_app.py"
name = "Overview"

[[pages]]
path = "pages/1_Team_Odds.py"
name = "Team Odds"

[[pages]]
path = "pages/2_Group_Winners.py"
name = "Group Winners"

[[pages]]
path = "pages/3_Match_Predictor.py"
name = "Match Predictor"

[[pages]]
path = "pages/4_Bracket.py"
name = "Bracket"
